CREATE DATABASE customer_behavior;
show databases;
use customer_behavior;
show tables;

SELECT * FROM customer_shopping LIMIT 20;

-- total revenue generated by male V/s female?
select gender , sum(purchase_amount) as revenue
from customer_shopping
group by gender;

-- which customer used discount but still spend more than avg purchase amount
select customer_id, purchase_amount
from customer_shopping
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_shopping);

-- which are the top 5 products with highest avg review
select round(avg(review_rating),2) as "Average Product Rating", item_purchased
from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- avg purchase_amt between standard and express shipping compare
select avg(purchase_amount) as "Amount Purchased", shipping_type
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type;

-- compare between subscribers and non-subscribers using avg spend and total revenue
select subscription_status, round(avg(purchase_amount),2) as spend, round(sum(purchase_amount),2) as revenue,
count(customer_id) as total_customer
from customer_shopping
group by subscription_status
order by revenue, spend desc ;

-- which 5 products have the highest percentage of purchases with discounts applied
select item_purchased, 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer_shopping
group by item_purchased 
order by discount_rate desc
limit 5;

-- segment customers into new, returning and laoyal based on the total number of previousa purchases and count each segment
with customer_type as(
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_shopping
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- top 3 most purchased products in each category
with item_counts as(
select category,
item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer_shopping
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <= 3;

-- are customers who are repeat buyers also likely to subscribe

select subscription_status, 
count(customer_id) as repeated_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status; 

-- revenue contribution by each age group
select age_grp, sum(purchase_amount) as revenue
from customer_shopping
group by age_grp
order by revenue desc;
